### ISSUE TITLE
Syntax Highlighting Selection from Text Editor

### ISSUE THREAD

**Issue by jonluca** [jonluca/PasteBinApp#6]
A nice improvement would be if we could select a new syntax on the actual text Create A Paste view, when we are typing. Perhaps next to the Submit button, we could have a drop down or new view controller for the syntax.

**Comment by Aecasorg** [comment]
When you say 'new syntax', do you mean choosing the language of the syntax highlighter or style? Or have I completely missed the point of what you are asking? :)

**Comment by jonluca** [comment]
Yes exactly that.

Just so if you’re writing in Ruby and it’s currently set to C++, you don’t
have to exit the editor, go to settings, change it to Ruby, and then go
back to the editor.

**Comment by Aecasorg** [comment]
Gotcha!

However, I set it to automatic, although I have not tested that. Don't know how accurate that is. Maybe manual control feels better?

**Comment by Aecasorg** [comment]
Nope, you're right. The automatic detection does not work so well. Better to have manual control.

**Comment by Aecasorg** [comment]
OK, something's come up that I need your input for. 

The languages/syntax supported by pastebin.com is NOT the same as the ones supported by the Highlightr framework (syntax highlighter). Do we force only one language list (i.e. make a new array of languages that only holds the languages/syntax that BOTH pastebin and Highlightr support) to be used or separate them leaving the pastebin language in the Options view and only use the highlighter for the pasteview so the user can see it on screen but nothing else? I can try and set it so that the syntax selector in the pasteview (I've done a popup picker view for that) tries to grab the language that is set from the options menu but if not compatible it just comes up with default unless you set it yourself when editing.

If all that made sense, what do you think?

**Comment by jonluca** [comment]
I think the latter option would be the best user experience - we let them chose what Pastebin language they want, and if it's available in Highlightr then we do syntax highlighting with that language. Otherwise, just show default.

The best way of doing that IMO would just be to have a map of all the Pastebin->Highlightr languages. Any languages that aren't in highlightr just map to Default.
So it would look something like this:

```
{
  "c++": "C++",
  "ruby": "Ruby",
  "randomPasteBinLanguageThatDoesntExist": "Default"
}
```

Where they key is the pastebin lang and the value is the highlightr language.

**Comment by Aecasorg** [comment]
Ok, sure makes sense. 

What happens when a syntax it is available in HIghlightr but not Pastebin's library? How would we portray that? Or just consider Pastebin's list as the "master list" and ignore the rest?

I'm having to manually go through and match the entries of the arrays from each to make a new dict. Would you mind if I sent you the lists so you can double check and see if there are any languages that I missed or should be matched but are just called by a different name that I do not happen to know?

**Comment by jonluca** [comment]
Yeah I say we have the paste bin list be the master list.

And sure - thanks for doing this!

**Comment by Aecasorg** [comment]
Here are the lists:

Pastebin "master" list (dictionary): https://pastebin.com/H7ikEGzT
There are many missing languages and I have put the ones that I could match. Please see if there's anything I have missed from the list below.

Hightlightr array: https://pastebin.com/ppfmntyb
These are the syntaxes that I can't find a matching pair from the Pastebin list above. 

Thanks!
Henrik

**Comment by jonluca** [comment]
This looks great! I only noticed a few things.

1. [TypoScript](https://docs.typo3.org/typo3cms/TyposcriptSyntaxReference/8.7/AppendixA/Index.html) isn't typescript
2. Rails is Ruby, I think
3. jQuery is JavaScript
4. ECMAScript is JavaScript
5. All the C/C++ PasteBin langs should just match to "cpp"

**Comment by Aecasorg** [comment]
Thanks! 

I did wonder where all the C#/C++ should go.
